export const sessionDemoCopy = {
  "zh-CN": {
    scenarios: {
      discuss: {
        name: "材料与讨论",
        steps: ["各自的材料", "汇入空间", "引用讨论", "Agent 辅助"],
        short: ["材料", "发布", "讨论", "Agent"],
        captions: [
          "Lin、Mei 和 Kai 各自选一段已经完成的会话。不同 Agent 的发现，从这里走到一起。",
          "同事通过邀请加入，各自预览并发布选定的材料。个人会话继续保留，新内容由作者决定何时再分享。",
          "引用三份材料的具体版本，在原文旁讨论。材料更新后，已有引用仍保留当时的版本。",
          "Mei 让自己的 Claude Code 通过 MCP 按需读取材料、核对依据并回复，继续使用自己的个人会话。",
        ],
        actions: [
          "把选定材料带进来",
          "看看大家如何讨论",
          "让个人 Agent 帮忙核对",
          "重新看材料汇入",
        ],
      },
      execute: {
        name: "输入接力",
        steps: ["启用执行", "开放访问", "交接输入", "原生继续", "交还输入"],
        short: ["启用", "访问", "交接", "继续", "交还"],
        captions: [
          "需要一起动手时，Lin 确认来源、工作目录与权限模式，创建新的原生协作 fork。材料与讨论继续保留。",
          "Lin 向 Mei 明确开放完整原生历史与工作目录。访问已开放，输入仍然归 Lin。",
          "Lin 将输入交给 Mei。当前输入者变了，执行主机保持不变，Kai 仍可继续阅读与讨论。",
          "Mei 在对应的 Codex 原生客户端继续输入。模型调用、代码修改与执行都在 Lin 的 Mac。",
          "完成这一段，Mei 把输入交还给 Lin。大家贡献的材料与讨论仍在，沿着这次工作继续。",
        ],
        actions: [
          "向 Mei 开放执行访问",
          "把输入交给 Mei",
          "看看 Mei 如何继续",
          "Mei 交还输入",
          "重新看输入接力",
        ],
      },
    },
    materials: [
      {
        id: "lin",
        author: "Lin",
        provider: "Codex",
        title: "登录回跳调查",
        range: "第 2—3 轮",
        question: "登录后，为什么会跳到外部地址？",
        finding: "回跳参数缺少同源校验。",
        reference: "Lin 的调查 · v1",
      },
      {
        id: "mei",
        author: "Mei",
        provider: "Claude Code",
        title: "外部地址复现",
        range: "第 4—5 轮",
        question: "试一下外部 URL 和 // 开头的地址。",
        finding: "两种写法都能复现，需要一起检查。",
        reference: "Mei 的复现 · v1",
      },
      {
        id: "kai",
        author: "Kai",
        provider: "Codex",
        title: "站内跳转约定",
        range: "第 1—2 轮",
        question: "哪些登录后的回跳路径需要保留？",
        finding: "合法的站内路径应继续保留。",
        reference: "Kai 的约定 · v1",
      },
    ],
    bridge: {
      discussTitle: "各自的发现，一起用",
      discussLabels: ["材料", "引用", "讨论"],
      executeTitle: "同一个协作会话",
      executeLabels: ["原生 fork", "输入接力"],
    },
    source: {
      sessionLabel: (author: string) => `${author} 的 Session`,
      personalDescription: "同事已经做过的复现",
      hostDescription: "从已经做过的调查开始",
      outsideRange: "先前的对话未选入本次分享",
      publicRange: "本次公开范围",
      personalFirstTurn: "04 · 尝试复现",
      hostFirstTurn: "02 · 定位问题",
      personalSecondTurn: "05 · 核对结果",
      hostSecondTurn: "03 · 核对实现",
      agentChecked: "按 Mei 的指令，已核对三份共享材料",
      previewFirst: "选好这一段，预览后再发布",
      published: (title: string) => `${title} v1 · 已发布`,
      sessionKept: "个人会话继续保留",
      scopeOwned: "公开范围由自己决定",
    },
    discussion: {
      contributorSelected: "选定第 1—2 轮",
      contributorPublished: "已发布 v1",
      headingBefore: "各自选一段，带进这次讨论。",
      headingAfter: "同一个空间，三个人的发现。",
      statusBefore: "已选片段 · 可点开预览",
      statusAfter: "已发布材料 · 可查看固定版本",
      materialsAriaLabel: "查看各自的会话材料",
      preview: "预览",
      prePublishPreview: " · 发布前预览",
      returnToDiscussion: "返回讨论",
      collapseExcerpt: "收起片段",
      agentReplyLabel: "Mei 的个人 Claude Code · MCP 辅助回复",
      citationLabel: "Kai · 引用大家的发现",
      agentReply:
        "已按 Mei 的要求核对三份材料：检查外部 URL 和协议相对地址，同时保留合法站内路径。",
      citationReply:
        "Lin 找到了原因，Mei 补上了复现。结合站内跳转约定，这次修改也要保留合法路径。",
      noteBefore:
        "你带来定位过程，同事补上复现与约定。从各自做过的工作开始。",
      noteAfter:
        "三份材料都有各自的作者和版本。一起阅读、引用和讨论，无需交接输入。",
      readOnlyStatus: "只读分享 · 后续对话由作者主动发布",
    },
    execution: {
      events: [
        "已从选定来源创建新的协作 fork",
        "已向 Mei 开放执行访问 · 输入仍在 Lin",
        "输入已交给 Mei · 等待 Mei 的下一步输入",
        "Mei 已提交输入 · 正在 Lin 的 Mac 上处理",
        "Mei 已交还输入 · Lin 可以继续",
      ],
      oneWriter: "同一时刻，一位当前输入者",
      executionHost: "执行：Lin 的 Mac",
      currentWriterAria: (writer: string) => `当前输入者：${writer}`,
      currentInput: "当前输入",
      hostCanReclaim: "发起者 · 可以接回",
      canContinue: "可以继续输入",
      returnDirection: "← 交还",
      handoffDirection: "交接 →",
      accessWaiting: "已获访问 · 等待交接",
      discussionOnly: "阅读与讨论",
      hostSession: "Lin 的协作会话",
      taskTitle: "修复登录回跳",
      nativeFork: "~/projects/checkout · 新的原生 fork",
      taskPrompt: "补上同源校验，并保留合法站内路径。",
      waitingPrompt: "材料与讨论都在，等待下一步输入。",
      handedToMei: "输入已交给 Mei · Lin 继续查看",
      linCanType: "Lin 可以输入下一步…",
      staysOnMac: "会话与执行留在这台 Mac",
      viewing: "查看中",
      currentWriter: "当前输入者",
      nativeClient: "Mei 的原生客户端",
      collaborationView: "Mei 的协作视图",
      headings: [
        "讨论之后，一起继续",
        "访问已开放，输入还没交接",
        "这一段，交给 Mei",
        "在熟悉的客户端里处理",
        "处理好了，交还输入",
      ],
      nativeClients: "原生 TUI / 专用 Codex Desktop",
      materialsRemain: "原有材料和讨论继续保留",
      messages: [
        "Lin 启用共同执行，Mei 和 Kai 仍可继续阅读、发布材料与讨论。",
        "Mei 获得完整原生历史与工作目录访问，等待 Lin 明确交出输入。",
        "输入已交到 Mei 手里，可以在对应的 Codex 客户端继续这次工作。",
        "补上同源校验，并保留合法的站内回跳路径。",
        "这一段已经处理好，交还给 Lin 继续下一步。",
      ],
      agentResponse: "接入共享的 Codex 会话，个人 Claude Code 材料继续保留。",
      meiDone: "Mei：这一段处理好了。",
      meiCanType: "Mei 可以输入下一步…",
      keepDiscussing: "查看共享进展，继续参与讨论",
      annotationLabel: "Kai · 讨论继续",
      annotation: "记得保留合法的站内回跳路径。",
      nativeCurrentWriter: "原生客户端 · 当前输入者",
      discussionOpen: "阅读与讨论继续开放",
      canType: "可以输入",
      inputWithLin: "输入在 Lin",
      othersContinue: "其他成员可以一直阅读、发布材料与讨论。",
    },
    controls: {
      stepsAria: (name: string) => `${name}演示步骤`,
      stepAria: (name: string, index: number, label: string) =>
        `${name}第 ${index} 步：${label}`,
      scrollHint: "继续向下滚动，逐步看完材料与讨论、输入接力。演示结束后页面自然继续。",
      manualHint: "点击步骤逐段查看，或按播放按钮观看当前演示。",
      playbackAria: (playing: boolean, name: string) =>
        `${playing ? "暂停" : "播放"}${name}演示`,
      demoOnly: "（演示）",
    },
    heading: {
      overline: "协作演示",
      sample: "示例内容",
      discussTitle: "各自的 Agent 材料，一起用起来。",
      executeTitle: "下一步，交给 Ta 继续。",
      tabsAriaLabel: "选择协作演示场景",
      discussTab: "材料与讨论",
      executeTab: "输入接力",
    },
    takeaways: {
      discussPrimary: "阅读和讨论，本身就是一次完整的协作。",
      discussSecondary: "选定范围 · 固定版本 · 各自贡献",
      executePrimary: "执行留在发起者主机，各自使用自己的客户端。",
      executeSecondary: "新的原生 fork · 明确开放访问 · 输入接力",
    },
  },
  en: {
    scenarios: {
      discuss: {
        name: "Material and discussion",
        steps: [
          "Choose material",
          "Publish to space",
          "Discuss citations",
          "Agent assist",
        ],
        short: ["Choose", "Publish", "Discuss", "Agent"],
        captions: [
          "Lin, Mei, and Kai each select part of a completed Session. Findings from different Agents come together here.",
          "Teammates join by invitation, preview their selected material, and publish it. Personal Sessions remain private; each author decides when to share anything new.",
          "The team cites exact versions of three materials and discusses them beside the source. Existing citations keep their original version after an update.",
          "Mei asks her personal Claude Code to use MCP to read the material on demand, check the evidence, and reply while staying in her own Session.",
        ],
        actions: [
          "Publish the selected material",
          "See how the team discusses it",
          "Ask a personal Agent to check",
          "Replay the material flow",
        ],
      },
      execute: {
        name: "Input handoff",
        steps: [
          "Enable execution",
          "Open access",
          "Hand off input",
          "Continue natively",
          "Return input",
        ],
        short: ["Enable", "Access", "Handoff", "Continue", "Return"],
        captions: [
          "When the team needs to act, Lin confirms the source, working directory, and permission mode, then creates a new native collaboration fork. Material and discussion remain available.",
          "Lin explicitly opens the full native history and working directory to Mei. Access is open, but Lin still holds input.",
          "Lin hands input to Mei. The current writer changes while the execution host stays the same, and Kai can keep reading and discussing.",
          "Mei continues in the matching native Codex client. Model calls, code changes, and execution all remain on Lin's Mac.",
          "When her part is done, Mei returns input to Lin. Everyone's material and discussion remain available as the work continues.",
        ],
        actions: [
          "Open execution access for Mei",
          "Hand input to Mei",
          "See how Mei continues",
          "Return input to Lin",
          "Replay the input handoff",
        ],
      },
    },
    materials: [
      {
        id: "lin",
        author: "Lin",
        provider: "Codex",
        title: "Sign-in redirect investigation",
        range: "Turns 2–3",
        question: "Why does sign-in redirect to an external address?",
        finding: "The redirect parameter has no same-origin check.",
        reference: "Lin's investigation · v1",
      },
      {
        id: "mei",
        author: "Mei",
        provider: "Claude Code",
        title: "External redirect reproduction",
        range: "Turns 4–5",
        question: "Try an external URL and a protocol-relative URL.",
        finding: "Both forms reproduce the issue and need the same check.",
        reference: "Mei's reproduction · v1",
      },
      {
        id: "kai",
        author: "Kai",
        provider: "Codex",
        title: "Internal redirect convention",
        range: "Turns 1–2",
        question: "Which post-sign-in redirect paths must keep working?",
        finding: "Valid internal paths should continue to work.",
        reference: "Kai's convention · v1",
      },
    ],
    bridge: {
      discussTitle: "Bring each finding together",
      discussLabels: ["Material", "Citations", "Discussion"],
      executeTitle: "One collaboration Session",
      executeLabels: ["Native fork", "Input handoff"],
    },
    source: {
      sessionLabel: (author: string) => `${author}'s Session`,
      personalDescription: "A reproduction your teammate already completed",
      hostDescription: "Start from an investigation already in progress",
      outsideRange: "Earlier conversation was not selected for this share",
      publicRange: "Published range",
      personalFirstTurn: "04 · Reproduce",
      hostFirstTurn: "02 · Locate the issue",
      personalSecondTurn: "05 · Check the result",
      hostSecondTurn: "03 · Check the implementation",
      agentChecked: "Checked all three shared materials at Mei's request",
      previewFirst: "Select this range, then preview before publishing",
      published: (title: string) => `${title} v1 · Published`,
      sessionKept: "Personal Session stays private",
      scopeOwned: "You control the published scope",
    },
    discussion: {
      contributorSelected: "Turns 1–2 selected",
      contributorPublished: "Published as v1",
      headingBefore: "Each person brings one selection into the discussion.",
      headingAfter: "One space, three people's findings.",
      statusBefore: "Selected ranges · Open to preview",
      statusAfter: "Published material · Fixed versions available",
      materialsAriaLabel: "View each teammate's Session material",
      preview: "Preview",
      prePublishPreview: " · Pre-publish preview",
      returnToDiscussion: "Back to discussion",
      collapseExcerpt: "Close excerpt",
      agentReplyLabel: "Mei's personal Claude Code · MCP-assisted reply",
      citationLabel: "Kai · Cites the team's findings",
      agentReply:
        "At Mei's request, I checked all three materials: reject external and protocol-relative URLs while preserving valid internal paths.",
      citationReply:
        "Lin found the cause and Mei reproduced it. Combined with the internal redirect convention, the fix also needs to preserve valid paths.",
      noteBefore:
        "You bring the investigation; teammates add a reproduction and a project convention. Start from work each person has already done.",
      noteAfter:
        "Each material has its own author and version. Read, cite, and discuss them together without handing off input.",
      readOnlyStatus: "Read-only sharing · Authors publish later turns deliberately",
    },
    execution: {
      events: [
        "Created a new collaboration fork from the selected source",
        "Opened execution access for Mei · Input remains with Lin",
        "Handed input to Mei · Waiting for Mei's next input",
        "Mei submitted input · Processing on Lin's Mac",
        "Mei returned input · Lin can continue",
      ],
      oneWriter: "One current input holder at a time",
      executionHost: "Execution: Lin's Mac",
      currentWriterAria: (writer: string) => `Current input holder: ${writer}`,
      currentInput: "Current input",
      hostCanReclaim: "Host · Can take input back",
      canContinue: "Can continue typing",
      returnDirection: "← Return",
      handoffDirection: "Hand off →",
      accessWaiting: "Access granted · Waiting for handoff",
      discussionOnly: "Reading and discussion",
      hostSession: "Lin's collaboration Session",
      taskTitle: "Fix the sign-in redirect",
      nativeFork: "~/projects/checkout · New native fork",
      taskPrompt: "Add the same-origin check and preserve valid internal paths.",
      waitingPrompt: "Material and discussion are ready. Waiting for the next input.",
      handedToMei: "Input is with Mei · Lin keeps watching",
      linCanType: "Lin can enter the next step…",
      staysOnMac: "Session and execution stay on this Mac",
      viewing: "Viewing",
      currentWriter: "Current input holder",
      nativeClient: "Mei's native client",
      collaborationView: "Mei's collaboration view",
      headings: [
        "Continue together after the discussion",
        "Access is open; input has not moved",
        "Hand this part to Mei",
        "Work in a familiar client",
        "Done with this part; return input",
      ],
      nativeClients: "Native TUI / dedicated Codex Desktop",
      materialsRemain: "Existing material and discussion remain available",
      messages: [
        "Lin enables collaborative execution. Mei and Kai can keep reading, publishing material, and discussing.",
        "Mei receives access to the full native history and working directory, then waits for Lin to hand off input explicitly.",
        "Input is now with Mei, who can continue the work in the matching Codex client.",
        "Add the same-origin check while preserving valid internal redirect paths.",
        "This part is complete. Return input to Lin for the next step.",
      ],
      agentResponse:
        "Connected to the shared Codex Session; personal Claude Code material remains available.",
      meiDone: "Mei: This part is done.",
      meiCanType: "Mei can enter the next step…",
      keepDiscussing: "Follow shared progress and keep discussing",
      annotationLabel: "Kai · Discussion continues",
      annotation: "Remember to preserve valid internal redirect paths.",
      nativeCurrentWriter: "Native client · Current input holder",
      discussionOpen: "Reading and discussion remain open",
      canType: "Can type",
      inputWithLin: "Input with Lin",
      othersContinue:
        "Other teammates can keep reading, publishing material, and discussing throughout.",
    },
    controls: {
      stepsAria: (name: string) => `${name} demo steps`,
      stepAria: (name: string, index: number, label: string) =>
        `${name}, step ${index}: ${label}`,
      scrollHint:
        "Scroll to step through both flows. The page continues after the demo.",
      manualHint: "Choose a step, or press play to watch the current flow.",
      playbackAria: (playing: boolean, name: string) =>
        `${playing ? "Pause" : "Play"} the ${name} demo`,
      demoOnly: "(demo)",
    },
    heading: {
      overline: "Collaboration demo",
      sample: "Example content",
      discussTitle: "Put everyone's Agent material to work.",
      executeTitle: "Hand the next step to a teammate.",
      tabsAriaLabel: "Choose a collaboration demo scenario",
      discussTab: "Material and discussion",
      executeTab: "Input handoff",
    },
    takeaways: {
      discussPrimary: "Reading and discussion are a complete collaboration.",
      discussSecondary: "Selected scope · Fixed versions · Everyone contributes",
      executePrimary:
        "Execution stays on the host machine while everyone uses their own client.",
      executeSecondary:
        "New native fork · Explicit execution access · Input handoff",
    },
  },
} as const;

export type DemoScenario = keyof (typeof sessionDemoCopy)["en"]["scenarios"];
